### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by MatheusCavalca**
Update fork with changes on [kakashidinho](https://github.com/kakashidinho)/[metalangle](https://github.com/kakashidinho/metalangle).

@jsvatek, I'd like to confirm this won't conflict or create inconsistencies with how the Balance projects are using MetalANGLE.

### CODE REVIEW

**Review by jerelevine — APPROVED** [review]
LGTM! @aab29 can you help verify that there are no concerning changes in the upstream update?

**Review by aab29 — APPROVED** [review]
I tried checking out this branch and testing it in `Achilles` and in `griffin`.  ✔️✔️ I'm mostly just sanity-checking things, but so far I haven't noticed anything concerning.  🆗 Seems like it should be okay to merge as long as we keep an eye out for any regressions it could have introduced!  :shipit:👁️👍

Note that this PR includes the changes from https://github.com/kakashidinho/metalangle/pull/84 , which possibly means we will be able to remove some of the workarounds (hacks) that we added to prevent the content scale from getting messed up whenever `viewWillAppear` or `viewDidLayoutSubviews` gets called on the MOAI game view controller.  🩹🗑️ When I noticed the PR on the upstream the other day, I already went ahead and created Jira tickets to do this: [Elevate](https://elevatelabs.atlassian.net/browse/GPE-22) and [Balance](https://elevatelabs.atlassian.net/browse/GPE-23).  🎟️ 🎟️ However, as far as I can tell, it won't cause any issues to leave those workarounds in place.  🆗

Another important thing to note is that this PR also includes [this commit](https://github.com/mindsnacks/metalangle/pull/3/commits/7360a44af2d9962bf101b934e64b14d299b3d8f3), which would exclude architectures for the Simulator on `master`.  🦖  I *think* that's fine?  But it's tricky because we **don't** want to exclude those architectures on Balance... so we'd need to remember that the next time we update Carthage over there.  🕸️

So plenty to think about and keep track of... but I'm pretty sure it's fine to merge.  ✔️

**Comment by MatheusCavalca** [comment]
@jsvatek, I'd love to have your input here. Does this PR conflict or create any issues with the way you guys are using MetalANGLE on Tatooine/Kamino?

**Comment by jsvatek** [comment]
@MatheusCavalca thanks for checking! @aab29 any chance you could sanity check on Balance quickly as well?

**Comment by jsvatek** [comment]
Ah, just noticed [the commit](https://github.com/mindsnacks/metalangle/pull/3/commits/7360a44af2d9962bf101b934e64b14d299b3d8f3) you flagged. Yeah, if that prevents running Balance in the simulator that would be a blocker.

**Comment by MatheusCavalca** [comment]
@aab29 and @jsvatek, I just noticed that the commit that is excluding arm64 is from myself. We can simply get rid of this commit on this PR and create a separate branch to contain changes that are needed for Griffin/CoreMS (excluding arm64 for example).

**Review by jsvatek — APPROVED** [review]

**Pull request merged**
